title: Organizations
modelClass: HeathDutton\Charity\Models\Organization
list: $/heathdutton/charity/models/organization/columns.yaml
recordUrl: 'heathdutton/charity/organizations/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
